# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\"\x1c\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"!\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2j\n\x0b\x46ileService\x12+\n\nUploadFile\x12\n.FileChunk\x1a\x0f.UploadResponse(\x01\x12.\n\x0c\x44ownloadFile\x12\x10.DownloadRequest\x1a\n.FileChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=22
  _globals['_FILECHUNK']._serialized_end=50
  _globals['_UPLOADRESPONSE']._serialized_start=52
  _globals['_UPLOADRESPONSE']._serialized_end=85
  _globals['_DOWNLOADREQUEST']._serialized_start=87
  _globals['_DOWNLOADREQUEST']._serialized_end=122
  _globals['_FILESERVICE']._serialized_start=124
  _globals['_FILESERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
